# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True),
        ),
    ]
