# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_calendar', '0002_auto_20160625_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisdiction',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set([('name', 'jurisdiction')]),
        ),
    ]
