# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('civic_calendar', '0004_auto_20160805_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
