# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civic_calendar', '0006_auto_20160907_1330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('name', 'city')]),
        ),
    ]
