# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic_calendar', '0009_auto_20170124_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.DateTimeField(verbose_name='meeting start date and time'),
        ),
    ]
